### ISSUE TITLE
Wrong indentation on ternary operator

### ISSUE THREAD

**Issue by FezVrasta** [prettier/prettier#1271]
I can't reproduce it on http://mib.im/try-prettier/, but if I run:

```
$(npm bin)/prettier --single-quote --trailing-comma es5 --write "{src,scripts,tests}/**/*.js"
```

On my [Popper.js](https://github.com/FezVrasta/popper.js), the file `src/tooltip/index.js` at line 59 will have:

```
    // get events list
    const events = typeof options.trigger === 'string'
      ? options.trigger.split(' ').filter(trigger => {
          return ['click', 'hover', 'focus'].indexOf(trigger) !== -1;
        })
      : [];
```

Note that the `return` line has wrong indentation.

**Comment by SimenB** [comment]
Try to repro on prettier.github.io/prettier/

But why is it wrong? That looks correct to me :smile:

**Comment by FezVrasta** [comment]
It has 10 spaces instead of 8.

I get the bug on the site you provided.

**Comment by SimenB** [comment]
(you can copy paste the url)

I still think it is correct, it's indented in the `filter` scope

**Comment by FezVrasta** [comment]
ESLint will throw an error, so I don't think it's correct.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%20%20%20%20%2F%2F%20get%20events%20list%5Cn%20%20%20%20const%20events%20%3D%20typeof%20options.trigger%20%3D%3D%3D%20'string'%5Cn%20%20%20%20%20%20%3F%20options.trigger.split('%20').filter(trigger%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20return%20%5B'click'%2C%20'hover'%2C%20'focus'%5D.indexOf(trigger)%20!%3D%3D%20-1%3B%5Cn%20%20%20%20%20%20%7D)%5Cn%20%20%20%20%20%20%3A%20%5B%5D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by SimenB** [comment]
IMO, that's a bug in eslint.

But you should disable styling rules in eslint which conflicts with prettier. You can use https://github.com/prettier/eslint-config-prettier to do that.

**Comment by FezVrasta** [comment]
It's not a bug, the indentation doesn't have "scope", it's just indentation.

**Comment by SimenB** [comment]
Do you think this is indented properly:

```js
options.trigger.split(' ').filter(trigger => {
return ['click', 'hover', 'focus'].indexOf(trigger) !== -1;
})
```
?

If you think it's correct, then I disagree with you. If you're in agreement with me that it should be

```js
options.trigger.split(' ').filter(trigger => {
  return ['click', 'hover', 'focus'].indexOf(trigger) !== -1;
})
```

then why should it be treated differently just because it's within a ternary?

**Comment by FezVrasta** [comment]
The indentation must always be:

````
something
  else
    with
      always
        2
          more
            spaces
```

You can't have:

```
something
   with
       four spaces
```

Honestly I'm a bit scared to have to discuss about this to one of the contributors of the most raging formatting library of the moment...

**Comment by SimenB** [comment]
I'm not a collaborator here, just a user like you 😄 

What prettier does here is aligning the closing brace to where the opening brace comes from (`options.trigger.split(' ').filter(trigger => {`) instead of the opening `?` in the ternary. I think that prettier's current behavior correct, while eslint thinks it should align with the `?`.

This looks like eslint/eslint#6606, so I think you either will have to disable the eslint rule (which makes sense in a prettier context) or see if one of the maintainers agrees with you that the current behavior is wrong.

**Comment by FezVrasta** [comment]
It doesn't make sense, because this is valid for both ESLint and Prettier instead:

```
    // get events list
    const events = typeof options.trigger === 'string'
      ? options.trigger.split(' ').filter(trigger =>
        return ['click', 'hover', 'focus'].indexOf(trigger) !== -1
      )
      : [];
```

Btw, for contributor I mean:

![image](https://cloud.githubusercontent.com/assets/5382443/25042130/e5908f4e-2115-11e7-8f60-46371d61022d.png)

**Comment by SimenB** [comment]
That badge is highly misleading! 😃

If you pass that code into prettier, you can see it collapses the newlines, so that indentation is not kept.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%20%20%20%20%2F%2F%20get%20events%20list%5Cn%20%20%20%20const%20events%20%3D%20typeof%20options.trigger%20%3D%3D%3D%20'string'%5Cn%20%20%20%20%20%20%3F%20options.trigger.split('%20').filter(trigger%20%3D%3E%5Cn%20%20%20%20%20%20%20%20%5B'click'%2C%20'hover'%2C%20'focus'%5D.indexOf(trigger)%20!%3D%3D%20-1%5Cn%20%20%20%20%20%20)%5Cn%20%20%20%20%20%20%3A%20%5B%5D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by FezVrasta** [comment]
Yes but it produces a valid indentation.

**Comment by SimenB** [comment]
Sure, but that is not really related to your original report about erroneous placement of the closing brace; the closing paren is inlined by prettier, so eslint doesn't complain anymore.

We can force a break: https://prettier.github.io/prettier/#%7B%22content%22%3A%22%20%20%20%20%2F%2F%20get%20events%20list%5Cn%20%20%20%20const%20events%20%3D%20typeof%20options.trigger%20%3D%3D%3D%20'string'%5Cn%20%20%20%20%20%20%3F%20options.trigger.split('%20').filter(trigger%20%3D%3E%5Cn%20%20%20%20%20%20%20%20%5B'click'%2C%20'hover'%2C%20'focus'%2C%20'somethingreallylongsoitbreaks'%5D.indexOf(trigger)%20!%3D%3D%20-1%5Cn%20%20%20%20%20%20)%5Cn%20%20%20%20%20%20%3A%20%5B%5D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

What's interesting with that output is that eslint is _really_ confused as soon as there is no braces there.

![image](https://cloud.githubusercontent.com/assets/1404810/25042319/6b297106-2117-11e7-8eee-acd7f36c9738.png)

It's only when I add back `{`, `return` and `}` that it complains.

![image](https://cloud.githubusercontent.com/assets/1404810/25042333/8ba9829a-2117-11e7-99dc-5c93b050c542.png)

So I'm back at calling it a bug in eslint 😄 `indent` doesn't some sophisticated enough, while prettier just plows through and ignores whatever input you have and formats it as it sees fit.

**Comment by jlongster** [comment]
We don't treat eslint as an authority to how to format things, so it's true that it doesn't really matter if eslint thinks it's wrong or not. You shouldn't be using any of eslint's formatting rules with prettier unless you are fixing them afterwards with `eslint --fix` to get a different style.

The core of the issue is that the `return` is indented 2 spaces relative to it's outer syntax (`options`). That's why it works that way.

There's no right or wrong here. While you think this code looks good:

```js
 const events = typeof options.trigger === 'string'
      ? options.trigger.split(' ').filter(trigger => {
        return ['click', 'hover', 'focus'].indexOf(trigger) !== -1;
      })
      : [];
```

To me it looks a little strange because the end curly brace is mis-aligned with the expression that it's closing. There's nothing dictating that every single line can only be indented by specifically 2 spaces. There are rare times where you want to align something specifically, requiring an additional space or so.

With all of that said, we are probably going to change ternary formatting, as discussed here: https://github.com/prettier/prettier/pull/1171 So this probably is going to change. It's difficult to find a good syntax for wrapping ternaries, and we'll continue to iterate on it.

**Comment by vjeux** [comment]
I'm going to close this and concentrate all the ternary discussions in https://github.com/prettier/prettier/issues/1271

**Comment by FezVrasta** [comment]
1271 is this issue 😅

**Comment by vjeux** [comment]
Arg fail :p

**Comment by Platane** [comment]
If I may add, it looks odd when you indent with 4 spaces, as the ternary still introduce a 2 space indent.
![indent](https://cloud.githubusercontent.com/assets/1659820/26343331/dc39acc4-3f9b-11e7-906b-8cadc6577bc2.png)

**Comment by tylerbwilliams** [comment]
The ending bracket is not misaligned with the expression it's closing, since the `?` can be considered part of that expression.  For example, you would not add the arbitrary indentation to the following, because the ending bracket does not need to be in the same *character column* ( which @Platane pointed out still doesn't work depending on tab width ):
```
var myFn = options.trigger.split(' ').filter(trigger => {
  return ['click', 'hover', 'focus'].indexOf(trigger) !== -1;
});
```

**Comment by vjeux** [comment]
https://github.com/prettier/prettier/issues/737 is the issue I was thinking about.

**Comment by MacKentoch** [comment]
I'm sorry I did not catch the fix or workaround for this issue.
Until now I just wrap an ugly `/* eslint-disable indent */` around ternary operators.

It would be very 😇 (*nice*) if someone could remind how to deal this.

**Comment by lydell** [comment]
@MacKentoch add `"indent": "off"` under `"rules"` in your .eslintrc!

**Comment by MacKentoch** [comment]
I hoped something less radical...

Alright so be it. 
Thanks @lydel

**Comment by j-f1** [comment]
@MacKentoch Prettier will automatically enforce an indentation style, so you don’t need the `indent` rule.

**Comment by MacKentoch** [comment]
@j-f1 that makes sense. Thank you!

**Comment by tylerbwilliams** [comment]
This is still a broken feature, since it doesn't work for those using 4 space indents as shown above.

**Comment by anilanar** [comment]
I'm guessing someone who's using 4 spaces must make a PR, otherwise this problem is pretty much ignored by majority of users/devs using 2 spaces.

**Comment by ikatyang** [comment]
FYI, ternary with 4-space is fixed in #3747.

<details>
<summary>1.10.2</summary>

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDdHNez3f9YA6UA-MQRZVfsWVNQ4xbeU2++sUqx79Vzz5CaUbvWETcIADQgIABxgBLaAGdkoVACctEAO4AFbQnUpUANwhKAJjLSqYyAGaoANqriyARltRgA1nAwAMryfkpQAObIMFoArp4g1hBgzm4eshEeWjAGvpEAtqhp7okAVqoAHgBCvgFBwagFcAAyEXAlGXJxMPI9AEydiWFa2cggXqheAJ6u0HbyWhEwAOo2MAAWyAAcAAyyixAeK77y44tw2eYdslpwAI5xSnd5qIXFSC6lsh4FSjHxRKqCKRVxwACKcQg8CGshgUzW1k2yAALHDfEpXCCAMIQApFcZQaA3EBxDwAFSmpi+HgAvrSgA)
```sh
--tab-width 4
```

**Input:**
```jsx
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
?
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
?
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
?
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
:
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
:
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
:
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

**Output:**
```jsx
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    ? aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      ? aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        ? aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        : aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      : aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    : aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa;

```

</details>
<details>
<summary>master</summary>

**Prettier pr-3747**
[Playground link](https://deploy-preview-3747--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBDdHNez3f9YA6UA-MQRZVfsWVNQ4xbeU2++sUqx79Vzz5CaUbvWETcIADQgIABxgBLaAGdkoVACctEAO4AFbQnUpUANwhKAJjLSqYyAGaoANqriyARltRgA1nAwAMryfkpQAObIMFoArp4g1hBgzm4eshEeWjAGvpEAtqhp7okAVqoAHgBCvgFBwagFcAAyEXAlGXJxMPI9AEydiWFa2cggXqheAJ6u0HbyWhEwAOo2MAAWyAAcAAyyixAeK77y44tw2eYdslpwAI5xSnd5qIXFSC6lsh4FSjHxRKqCKRVxwACKcQg8CGshgUzW1k2yAALHDfEpXCCAMIQApFcZQaA3EBxDwAFSmpi+HgAvrSgA)
```sh
--tab-width 4
```

**Input:**
```jsx
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
?
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
?
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
?
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
:
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
:
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
:
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

**Output:**
```jsx
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    ? aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        ? aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
            ? aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
            : aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        : aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    : aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa;

```

</details>

**Comment by nlindroos** [comment]
Is this behaviour for `--tab-width 4` correct and does it belong under the same topic?

**Input**
```js
const happy = true;

const myObj = {
    trouble: happy ? {
        single: true,
        married: false,
    } :
    {},
};
```

**Expected output**
```js
const happy = true;

const myObj = {
    trouble: happy
        ? {
            single: true,
            married: false
        }
        : {}
};
```


**Prettier's output**
```js
const happy = true;

const myObj = {
    trouble: happy
        ? {
              single: true,
              married: false
          }
        : {}
};
```

[Prettier playground example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEALAhgB3wE9MBeTGAJwFc4BuAHSicig0wFsiB5AIwCsymYE0xiKlCNV4AbOEhwFimAPzDR4zWgCWUAOZyFVWgBoNmsR1yVK2uABMFAM1wy0cM1E0BfTEnPC3p7edCAmIBD4MNroyKDWkgDuAArWCGjIILgAbhDa9mFZGMgubh4gvJS4YADWcDAAyvjVunrIxuX2EGAlru7huu6UMMlVela9ZeH8aAAeAEJVtfUNuBxwADK6cJP9EdQw+AcATLvlzZRDmby4vEQy0IX4trAA6vkw2MgAHAAM4c8IO5XlV8JlnnAhtkduFKHAAI7UbRw0a4ca4M7hdwcbTtGjlHT6OQARWoEHgmJAMFu73sn2QABZwlRcNoZK0AMIQDgTFBQaAwkDUdwAFVuGSQpXc3m8QA)

Notice the indentation for lines 6-7 being 14 and for line 8 being 10. I would expect these indentations to be 12 and 8, respectively, i.e. multiples of the indentation base.

**Comment by lydell** [comment]
@nlindroos That's how I've always written my ternaries as well, but not the way Prettier does it. Prettier always adds two extra spaces for alignment.

**Comment by alexmccabe** [comment]
This is definitely an issue for people using indent of `four spaces`. I am experiencing this issue right now. The following screenshot highlights this perfectly. There are two extra spaces on the final two lines of the ternary. 
![screenshot 2018-05-31 10 52 31](https://user-images.githubusercontent.com/2529110/40775786-d15ff7b8-64c0-11e8-8eeb-4ba9ae13db57.png)

**Comment by lydell** [comment]
@alexmccabe You forgot to mention _why_ it is a problem. The code in your screen shot looks nicely formatted.

**Comment by pronebird** [comment]
Is there any workaround to that problem? I am happy to configure eslint to accept that kind of formatting. It throws errors and wrecks the deployment for me.

**Comment by azz** [comment]
@pronebird [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier)

**Comment by pronebird** [comment]
@azz I had less problems without `eslint-config-prettier`, so I'd prefer to avoid it for now and just have this issue fixed and then my eslint config is pretty much what prettier outputs.

**Comment by azz** [comment]
Sure you're not confusing it with [`eslint-plugin-prettier`](https://github.com/prettier/eslint-plugin-prettier)? `eslint-config-prettier` will reduce the number of errors as it only disables rules.

**Comment by pronebird** [comment]
@azz oh yeah you're right, thanks a lot! 😅

**Comment by alexmccabe** [comment]
@lydell It's a problem because the second-to-last line is indented six spaces, and the last line is indented two spaces. This goes against every other piece of code in my codebase, and it doesn't look right to _me_.

**Comment by j-f1** [comment]
@alexmccabe It looks right to me, the contents of the ternary’s alternate is all indented from the `:`, which makes it line up visually.

**Comment by lydell** [comment]
It didn’t look right to me for a long time either.

**Comment by MacKentoch** [comment]
Yes this a matter of taste, so debate could last more than infinity.

I just gave up my own preference in indentation and followed prettier: nice advantage is we all write the same (think of new comers who will benefit that).

**Comment by alexmccabe** [comment]
@MacKentoch I came to the same conclusion, and tried to get VSCode to accept the Prettier way, but I could not for the life of me get it to supercede ESLint. But that's another issue entirely, and not related to this. 

Personally though, I would prefer that if the indent was four spaces, it kept to that. I do however see the logic behind why it's formatting the ternary the way it is.

**Comment by pronebird** [comment]
I think, visually it makes sense what `prettier` does. It bumps two spaces to align with `setTimeout` in example above. However, I am not sure how that looks for those who prefer tabs. Probably two spaces as well.

**Comment by joamag** [comment]
Is it possible to add an option on prettier that controls this behavior ? For me it makes sense to have both options.

**Comment by j-f1** [comment]
That’s unlikely @joamag. See [our option philosophy](https://prettier.io/docs/en/option-philosophy.html) for a better explanation.

**Comment by david-quadpro** [comment]
I use Prettier 1.13.4 and use: 

`{` 
`	"tabWidth": 4,`
`	"useTabs": true`
`}`

As you can see below, the teneray operator uses 2 **spaces** causing TSLint to complain. I am not really bothered about if the indent should be there or not but if in Prettier's opinionated view it should as extra indent, it should be using the indent settings of every other place.

![image](https://user-images.githubusercontent.com/13586902/42802413-8ec40e5c-89ab-11e8-925d-55cb8ee9402a.png)

I hope my setup highlights why many of us believe this to be a bug.

**Comment by j-f1** [comment]
We recommend using something like `tslint-plugin-prettier` to disable all formatting-related TSLint rules. I don’t think we’ll be changing this style (unless we completely change how ternaries are printed).

**Comment by david-quadpro** [comment]
Oh I get it, the aim is not to indent as such, its to align the rest of the lines within the ternary operator with the first text after the ? itself. This is therefore 2 spaces in, one for the ? and then the space between it and the condition.

In my case, the only way to achieve that aim and still use the normal indent character(s) would be to insert a tab between ? and environment:

![image](https://user-images.githubusercontent.com/13586902/42817968-5258a1a8-89d8-11e8-882b-570bc08a97ce.png)

tslint is happy but I agree that is an unusual use of white space in the middle of the lines.

I will leave it as a hard to resolve problem, apart from simply turning off many tslint rules.

**Comment by j-f1** [comment]
Is there a reason you’re wary of turning off formatting-related TSLint rules? Prettier should be able to handle the formatting all by itself.
