### ISSUE TITLE
Comments inside decorator arguments are moved to the wrong line

### ISSUE THREAD

**Issue by cmmartin** [prettier/prettier#1460]
Babylon seems to support decorators, but prettier incorrectly relocates comments inside of decorator arguments. Please see [this example](https://prettier.github.io/prettier/#%7B%22content%22%3A%22var%20x%20%3D%20100%5Cn%5Cn%40Hello(%7B%5Cn%20%20a%3A%20'a'%2C%20%2F%2F%20Comment%20is%20in%20the%20wrong%20place%5Cn%20%20%2F%2F%20test%5Cn%20%20b%3A%20'2'%5Cn%7D)%5Cnclass%20X%20%7B%5Cn%20%20%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22es5%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D). Notice that the comments are moved to the wrong lines.

### Input
```javascript
var x = 100

@Hello({
  a: 'a', // Comment is in the wrong place
  // test
  b: '2'
})
class X {
  
}
```

### Output

```javascript
var x = 100 // Comment is in the wrong place

// test
@Hello({
  a: "a",
  b: "2",
})
class X {}
```

```shell
$ prettier --version
1.2.2
```

**Comment by vjeux** [comment]
Thanks, looks like the comment binary search doesn't go through decorators

**Comment by vjeux** [comment]
Another issue

```js
@AutoSubscribeStore
//store in resub, is a class extends from StoreBase.
class HelloStore extends StoreBase {
    @autoSubscribe
    // this method should return a string type
    getHello():string {
        return this._helloString;
    }
}
```

outputs

```js
//store in resub, is a class extends from StoreBase.
@AutoSubscribeStore class HelloStore extends StoreBase {
  @autoSubscribe // this method should return a string type
  getHello(): string {
    return this._helloString;
  }
}
```

and then

```js
//store in resub, is a class extends from StoreBase.
@AutoSubscribeStore class HelloStore extends StoreBase {
  @autoSubscribe getHello(): string { // this method should return a string type
    return this._helloString;
  }
}
```

**Comment by vjeux** [comment]
The original problem is fixed, not the second one.

**Comment by faassen** [comment]
A note: if you use documentation.js to generate the docs, this is the difference between getting proper docs and bad docs talking about decorators. It works properly for methods now but the issue vjeux indicated with classes isn't fixed yet.
