### ISSUE TITLE
Vue Support

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#2097]
Let's start a master issue for all the related vue.js progress.

List of projects using Vue (based on tweet https://twitter.com/Vjeux/status/873726664630337536 ):

- https://github.com/gitlabhq/gitlabhq
- https://github.com/bootstrap-vue/bootstrap-vue
- https://github.com/ElemeFE/element/
- https://github.com/algolia/vue-instantsearch
- https://github.com/vuetifyjs/vuetify
- https://github.com/samiheikki/javascript-guessing-game
- https://github.com/phanan/koel
- https://bitbucket.org/sellvana/core/src/4231c995aff9785ca60a550b0ee06c286f4bf619?at=sn1
- https://github.com/search?utf8=%E2%9C%93&q=language%3AVue+stars%3A%3E1000&type=Repositories&ref=advsearch&l=Vue&l=

**Comment by AustinPaquette** [comment]
Just want to add this to the list 😁 https://github.com/vuetifyjs/vuetify

**Comment by vjeux** [comment]
Looks like we'll need to run some js expansion inside of `:class` value:

```vue
<template>
  <h2
    class="title"
    :class="{
      'issue-realtime-pre-pulse': preAnimation,
      'issue-realtime-trigger-pulse': pulseAnimation
    }"
    v-html="titleHtml"
  >
  </h2>
</template>
```

https://github.com/gitlabhq/gitlabhq/blob/master/app/assets/javascripts/issue_show/components/title.vue#L46-L49

**Comment by vjeux** [comment]
Template supports a lang attribute. https://github.com/vuetifyjs/vuetify/blob/master/src/components/carousel/Carousel.vue

```js
<template lang="pug">
  div(class="carousel")
    div(class="carousel__left")
      v-btn(icon v-on:click.native.stop="prev")
        v-icon chevron_left
...
```

**Comment by azz** [comment]
> Looks like we'll need to run some js expansion inside of :class value

Except that's not valid JS. The `{}` in this case would be parsed as a block, not an object. We'd need to wrap it with `()` before parsing.

**Comment by samtgarson** [comment]
Didn't want to open a new issue, but feel free to tell me to shove off if this isn't the place...

I've got the `parse5` parser up and running on my large (unfortunately not open source) Vue codebase, and it seems to work well for `script` tags in `.vue` files, but for `.js` files and the `template` part of my `.vue` files it just sticks everything on one long line... 

Is this expected? Should I be using the default parser for `.js` files separately? Is it just too early to be using this?! 

Would be happy to provide samples etc. if that would be helpful. Thanks for the great work so far!

**Comment by azz** [comment]
> Is it just too early to be trying out the master branch?!

The html5 printer is super bare-bones at the moment. We need to take the time to figure out how best to re-use some of the particularly fancy code that formats JSX.

**Comment by azz** [comment]
@karl @vjeux r.e. above comment. Can either of you think of any issues with the idea of transforming the `htmlparser2` AST into a [JSX AST](https://github.com/facebook/jsx/blob/master/AST.md#jsx-extensions-to-mozilla-ast-format), then just printing that?

First things that come to mind:
* Whitespace treatment
* `<!doctype>`
* Void elements

**Comment by richardtallent** [comment]
To start with, I'd love to just see Prettier work look inside <script> tags for a specified list of specified file extensions (which could easily default to including .vue, .html, .htm, .aspx, etc.).

Having prettier work on JS within <template> markup is a "nice to have," but just being able to do so in the script tags would solve at least 80% of the problem, should be VERY easy to implement, and would allow support for a large number of HTML-like files (not just Vue SFCs).

**Comment by Rayraegah** [comment]
@richardtallent we attempted to auto fix js inside <script> tags on .vue files for JSPrettier (a sublime text plugin). But text editor language support was a bit off https://github.com/vuejs/vue-syntax-highlight/issues/83. To have prettier work on JS in <script> tags for all html-like files would be fantastic!

**Comment by karl** [comment]
@azz I'd be really interested in seeing how we could re-use the work that we've been putting into JSX for HTML.

At the moment I don't know enough about vue or it's templates to know what form that re-use or sharing would take.

Converting the AST to look like JSX and then using the existing code would be interesting, I'm not sure how we'd deal with the differences that you've listed. I'd probably approach it by trying it out and seeing what might go wrong!

**Comment by karl** [comment]
@azz ☝🏻 I've opened an issue to discuss how we might solve the white space differences between JSX and HTML.

**Comment by lukepolo** [comment]
Another big project using vuejs thats open source that we would like to run prettier on 

https://github.com/voten-co/voten

**Comment by kaicataldo** [comment]
Hi! Trying to follow through relevant issues, but am unsure where things currently stand. This is a feature I'm particularly interested in and would love to help out!

**Comment by troglotit** [comment]
@kaicataldo you could start searching for commits from this folder/files https://github.com/prettier/prettier/tree/master/tests/multiparser_vue
Unfortunately, I couldn't understand how to test it against real files 😢 . Seems like build scripts have to be updated to use multiparsers, but not sure.

**Comment by Rayraegah** [comment]
Example of Vue js pretty print using jsbeautify https://github.com/LeslieYQ/vue-format

**Comment by jackysee** [comment]
I have written a simple node script to format the `<script>` section of vue file (actually any html-like file should do). I use it with the sublime text's build system.

https://medium.com/@jackysee/prettier-vue-file-with-sublime-text-475062375956

**Comment by trusktr** [comment]
There's a known solution coming soon, using eslint. See this comment: https://github.com/prettier/prettier/issues/2648#issuecomment-323973082

**Comment by trusktr** [comment]
Basically using both `eslint-plugin-script-tags` and `eslint-plugin-prettier` together will yield the exact result that you're looking for. You should be able to test using the branch of that pull request.

**Comment by trusktr** [comment]
I've already tested `eslint-plugin-script-tags` + `eslint-plugin-prettier` and linting works, just eslint's auto-fix mode doesn't come into play like it does with normal `.js` files. That pull request turns on `--fix` mode for "processor" plugins (f.e. `eslint-plugin-script-tags`), which will make `eslint-plugin-prettier`'s fixes automatically apply.

**Comment by QuentinRoy** [comment]
@trusktr, this is nice! Though I wish we did not had to rely on `eslint --fix` to "prettierize" vue files..

**Comment by azz** [comment]
That's great!

This issue also tracks reformatting the HTML as well as the JS inside the script tags.

**Comment by yacinehmito** [comment]
@trusktr I tried your solution and it doesn't seem to work for me. ESLint complains about line-breaks that an auto-fix don't solve. Also, all the rules of `eslint-plugin-vue`that should be triggered in `template`are simply ignored.

I would very much like an update on this issue and any pointer to where to start in order to help.

**Comment by kaicataldo** [comment]
I finally had some time to look a bit at this, and was pleasantly surprised to find that it already seems to just work with the multiparser behavior. Reading through this issue, I was under the impression it hadn't been implemented yet! For my own understanding, what still needs to be done? Happy to help out :)

**Comment by samtgarson** [comment]
@kaicataldo My issues appear to be with Pug and Sass only, I've made a gist demonstrating this. https://gist.github.com/samtgarson/6cce2b7df9f5ba6c5b0ccf722c3fe588

However I tried with HTML as well rather than Pug and there seemed to still be issues with line breaks... 🤔

**Comment by lydell** [comment]
@samtgarson Prettier support neither the indented Sass syntax nor Pug.

**Comment by samtgarson** [comment]
@lydell [gist](https://gist.github.com/samtgarson/6cce2b7df9f5ba6c5b0ccf722c3fe588) updated to use HTML and CSS—still getting some weird linespace issues.

**Comment by lydell** [comment]
@samtgarson I have no idea how HTML/Vue formatting works in Prettier, just wanted to clarify that indented Sass and Pug are not supported.

**Comment by jonataswalker** [comment]
Is there anyone working on this?

**Comment by suchipi** [comment]
I think we were hoping to leverage https://github.com/prettier/prettier/pull/2976 to do this, once it's completed

**Comment by joseluisq** [comment]
One more Vue fan! 
I can't wait to try this feature! :+1:

**Comment by flybayer** [comment]
I got Prettier working for `<script>` tags in my `.vue` files using the following setup:

Packages:
```
eslint 
eslint-plugin-html
eslint-plugin-prettier
eslint-config-prettier
```

Eslint config:
```json
  "eslintConfig": {
    "extends": [
      "eslint:recommended",
      "prettier"
    ],
    "plugins": [
      "prettier",
      "html"
    ],
    "rules": {
      "prettier/prettier": [
        "error",
        {
          "printWidth": 90,
          "semi": false,
          "trailingComma": "es5",
          "bracketSpacing": false,
          "singleQuote": true
        }
      ],
      "camelcase": [
        "error",
        {
          "properties": "never"
        }
      ]
    }
  }

```

Run using:
```bash
eslint --ext .js,.vue src --fix
```

**Comment by jonataswalker** [comment]
Great @flybayer but `eslint-plugin-html` is not compatible (anymore) with `eslint-plugin-vue`.

**Comment by yacinehmito** [comment]
@flybayer Your configuration will only enable `prettier` for the `script` part. You will not get any linting for the `template` part.

**Comment by flybayer** [comment]
Yes, my solution is only temporary until we get proper Vue support.

@yacinehmito, right, I wrote that it only works for `<script>` tags.

**Comment by Anahkiasen** [comment]
For the note, as for a bunch of people in this issue, I care a _lot_ less about Prettier's ability to format Vue templates than I care about the ability for Prettier to format supported languages in `.vue` files. I don't necessarily care if my HTML is not formatted right, but I do care about my CSS/JS code next to it.

**Comment by trusktr** [comment]
I think properly indebted HTML is important too, tagged less brain cycle to process.

**Comment by Anahkiasen** [comment]
No yeah of course, what I mean is if Vue support were to be released in two times, with support for .vue files first then Vue templating, I'd appreciate getting JS/CSS formatting earlier instead of having to wait for the final part of it

**Comment by noscript** [comment]
This is how I format my vue projects, assuming everything is under `src/`:
```sh
#!/bin/bash -e
PROC="./node_modules/prettier/bin/prettier.js"
DIR="src"
format() {
  find $DIR -iname "*.vue" -print -exec sh -c "\
    sed -n '/^${1}/,/${2}/p' {} | \
    sed '1d;\$d' | ${PROC} --stdin-filepath dummy.${3} | \
    sed -e '1i${1}' -e '\$a${2}' | \
    sed -i -e '/^${1}/r /dev/stdin' -e '/^${1}/,/${2}/d' {} \
  " \;
}
$PROC --write $DIR/**/*.js webpack.config.js
format "<style lang=\"scss\">" "<\/style>" "scss"
format "<style>" "<\/style>" "css"
format "<style scoped>" "<\/style>" "css"
format "<script>" "<\/script>" "js"
```

How it works, it extracts `<script>...</script>` or `<style>...</style>` sections (section tags required to not have any leading whitespace, just to be safe), feeds each section separately to `prettier`,  and puts it back.

My `.prettierrc.json`:
```json
{
  "bracketSpacing": true,
  "printWidth": 80,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "useTabs": false
}
```

Disadvantage is that it processes each file multiple times, but the goal was to keep the script stupid simple and throw it away once prettier can format HTML5 properly.

**Comment by DerJacques** [comment]
Just FYI, the [vetur](https://github.com/vuejs/vetur/) extension for VS Code supports formatting `<script>` tags based on prettier-eslint out of the box.

Not sure if this may help implementing this for prettier more generally, but it definitely improves the coding experience for developers using VS Code. :)

**Comment by yacinehmito** [comment]
> Just FYI, the vetur extension for VS Code supports formatting <script> tags based on prettier-eslint out of the box.

Do you know if this is documented somewhere? I can't get it to work alongside `eslint-plugin-vue`.

**Comment by DerJacques** [comment]
They have a section om formatting in their documentation:
https://vuejs.github.io/vetur/formatting.html

Hope that helps!

**Comment by bencodezen** [comment]
Just wanted to post a +1 for Prettier working on the part of a Vue file. Would love to submit a PR, but could use some pointers on how one might get started understanding how to do this.

**Comment by pearofducks** [comment]
I extended @noscript's awesome work into a more [robust shell script](https://gist.github.com/pearofducks/22aa906a550c762a7b7a582f6d4e14ff) since it seems like this won't get fixed quickly. Any improvements are welcome!

- checks for the right `sed`
- can be run against a single file
- can be run in "check mode" to exit with an error if file content doesn't match what prettier would do (good for CI checks)
- only works against `<script>` tags (can easily be modified to use the others again)

**Comment by oligot** [comment]
Following @pearofducks's great work, I just published a Node.js package (so that it works on Windows too) that allows to format .vue files: https://github.com/oligot/vue-prettier

The main differences with [prettier-vue](https://github.com/guilhermelimak/prettier-vue) are
* Uses [vue-template-compiler](https://www.npmjs.com/package/vue-template-compiler) instead of regexp to parse .vue files
* same CLI args as prettier, so that it can be used as a drop-in replacement for now

I've also documented [how to integrate it with editors like Vim and Webstorm](https://github.com/oligot/vue-prettier#editor-integration).

**Comment by bencodezen** [comment]
That's awesome @oligot! Let me know if you get a VS Code Extension for it running and I'll be glad to test it out!

**Comment by oligot** [comment]
@bencodezen I forgot to mention, but Visual Studio Code supports formatting .vue files thanks to the [Vetur extension](https://vuejs.github.io/vetur/).
More informations can be found in the [formatting page](https://vuejs.github.io/vetur/formatting.html).

**Comment by bencodezen** [comment]
@oligot It seems like the HTML portion is still not supported yet if I'm not mistaken. They were using `js-beautify-html` at one point but it's now deprecated. I tried configuring it to use `prettier` but it only accepts the value of `none` and `js-beautify-html`

**Comment by web-padawan** [comment]
Both HTML `<template>` and JS in `<script>` tags support would be a huge feature for Polymer developers as well especially because we are not able to rely on existing Vue-specific tooling.

**Comment by web-padawan** [comment]
@pearofducks the script works perfectly but I am wondering if it could leave top level indentation untouched? e. g. having the snippet like this:
```html
<script>
  class MyButton extends HTMLElement {
  }
</script>
```
I would like not to change indentation but the result looks like this:
```html
<script>
class MyButton extends HTMLElement {
}
</script>
```

**Comment by pearofducks** [comment]
@web-padawan this is against Vue standard/best practices, so I don't think it should be part of something as opinionated as `prettier`

you should be able to create a version that satisfies this requirement using the output from [this line](https://gist.github.com/pearofducks/22aa906a550c762a7b7a582f6d4e14ff#file-pretty-vue-sh-L20), and just adding some spaces to each line as you'd prefer

**Comment by kaicataldo** [comment]
I was playing around with this a while back and Prettier was actually able to parse and format Vue files using its multi-parser capabilities and starting `*.vue` files with the HTML parser. There were some bugs in the formatting, but it seems to me like these could be fixed up. Would a PR that gets initial support for `*.vue` files (knowing that it's not ready for primetime yet) be helpful to this end?

**Comment by oligot** [comment]
@bencodezen According to issue #1882, prettier supports basic HTML.
I tried it in vue-prettier but it doesn't do anything 😕

**Comment by oligot** [comment]
Trying out [Integrating Prettier with ESLint](https://prettier.io/docs/en/eslint.html), I just found that it's possible to lint the script part of .vue files with prettier, without using the vue-prettier project.

I've created a small repo to show how it works (using both [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) and [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue)): https://github.com/oligot/vue-prettier-eslint

You can even use `eslint --fix` to fix the script part with prettier 🙌

**Comment by azz** [comment]
@kaicataldo absolutely!

**Comment by SteveALee** [comment]
I haven't got it to work at all in VS code with format on save. My eslintrc extends standard but when I save a .vue file semicolons get added :(

**Comment by bencodezen** [comment]
@SteveALee Do you have Prettier preferences set within your User Settings in VS Code? This is what mine looks like:

```
{
	"editor.detectIndentation": true,
	"editor.fontFamily": "Operator Mono",
	"editor.fontSize": 17,
	"editor.formatOnSave": true,
	"editor.formatOnPaste": true,
	"editor.wordWrap": "on",
	"workbench.colorTheme": "Cobalt2",
	"prettier.singleQuote": true,
	"prettier.semi": false,
	"prettier.useTabs": true,
	"prettier.tabWidth": 4,
	"prettier.trailingComma": "none",
	"prettier.eslintIntegration": true,
	"prettier.ignorePath": "package.json",
	"files.associations": {
		"*.js": "javascriptreact"
	},
	"workbench.startupEditor": "welcomePage",
	"files.autoSave": "off",
	"sublimeTextKeymap.promptV3Features": true,
	"editor.multiCursorModifier": "ctrlCmd",
	"editor.snippetSuggestions": "top",
	"window.zoomLevel": 0,
	"[javascript]": {}
}
```

**Comment by SteveALee** [comment]
No. I'm using the the Prettier VSCode extension and have [this setup](https://github.com/vuejs/vetur/issues/608).

It turns out the VSCode Prettier extension can use uses eslint and editorconfig settings and I really want the vuter extension to do the same in vue files as I get in .js files.

**Comment by LucienLee** [comment]
@oligot However, prettier still doesn't work with[`eslint-plugin-vue@next`](https://github.com/vuejs/eslint-plugin-vue), which have more concrete style guild. Your test project is based on `eslint plugin vue` 2.0.0.

**Comment by jasonxia23** [comment]
Error throws in `.vue` file.
```bash
SyntaxError: Unexpected token (2:30)
  1 | <template>
> 2 |   <transition name="confirm" @after-leave="leaveComplete" appear name="confirm">
    at createError$1 (myproject/node_modules/prettier/parser-babylon.js:1:112)
    at parse (myproject/node_modules/prettier/parser-babylon.js:1:878)
    at Object.parse$1 [as parse] (myproject/node_modules/prettier/index.js:5837:12)
    at formatWithCursor (myproject/node_modules/prettier/index.js:27654:22)
    at format (myproject/node_modules/prettier/index.js:27697:10)
    at Object.format (myproject/node_modules/prettier/index.js:27936:12)
    at Program (myproject/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:374:45)
    at listeners.(anonymous function).forEach.listener (myproject/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
```
I use eslint-plugin-vue@4.x.

**Comment by vjeux** [comment]
@jasonxia23 It tries to parse the vue (html) file with the Babylon (javascript) parser which doesn't work. The vue file support has not yet landed in prettier (we will do a release on Wednesday), so until then it's not going to work.

**Comment by jasonxia23** [comment]
Seems `.prettierignore` doesn't not work for `eslint-plugin-prettier`.
How can I ignore `*.vue` for `eslint-plugin-prettier`.

**Comment by azz** [comment]
@jasonxia23  Use `.eslintignore`.

**Comment by fengerzh** [comment]
@jasonxia23 Upgrade to Prettier 1.10 solved my problem.

**Comment by yacinehmito** [comment]
Should the issue be closed?

**Comment by j-f1** [comment]
@yacinehmito Not yet — we don’t format anything except the contents of `<script>` and `<style>` blocks.

**Comment by web-padawan** [comment]
How about my comment above regarding Polymer support? At least the contents of `<script>` tag should be similar thing.

**Comment by j-f1** [comment]
@web-padawan Can you open a new issue? If it’s as simple as doing the same thing to `.html` files that we do to `.vue` files, it shouldn’t be that difficult to get something that works until we figure out HTML support.

**Comment by skyrpex** [comment]
@fengerzh I'm using `"prettier": "^1.10.2",` and still crashes with vue files for me.

**Comment by vjeux** [comment]
@skyrpex could you create a separate issue for it? This way we can investigate it properly. Thanks!

**Comment by skyrpex** [comment]
Sorry, false alarm. I got it working using this specific configuration:

```yaml
extends:
  - plugin:vue/recommended
  - standard
  - prettier
  - prettier/standard
plugins:
  - vue
  - standard
  - prettier
# this is the most important part!
parserOptions:
  parser: babel-eslint
  ecmaVersion: 2017
  sourceType: module
rules:
  prettier/prettier: error
```

Source: https://github.com/prettier/prettier-eslint/issues/94#issuecomment-358308911

**Comment by fengerzh** [comment]
I think this issue can be closed now. Prettier does support Vue.js now.

**Comment by j-f1** [comment]
@fengerzh Not entirely — we don’t yet support formatting the HTML tags in `.vue` files.

**Comment by fengerzh** [comment]
According to #651, HTML won't be supported by Prettier, it was closed.

**Comment by lydell** [comment]
@fengerzh That issue is from when Prettier was only about 2 months old, and the scope of Prettier was not known/decided yet. Today, Prettier even has built-in (though hidden) experimental support for HTML! There’s just a lot to do before it’s ready to use.

**Comment by fengerzh** [comment]
Well, I'd love to see Prettier can reformat HTML. Plus, I hope it can also reformat CSS too, as there are CSS style code in .vue files.

**Comment by lydell** [comment]
@fengerzh Prettier can already format CSS! (Although it’s a bit rough around the edges sometimes.)

**Comment by evilebottnawi** [comment]
I am working on better `css/less/scss` formatting :star:

**Comment by fengerzh** [comment]
Ah, right, I did not notice that. That's really cool. Thank you!

**Comment by igeligel** [comment]
Is support for the [Vue.js Style Guide](https://vuejs.org/v2/style-guide/) planned?

I know that the `<template></template>` part is still not supported and it would be nice to have support for this but some things can be implemented already.

For example what we could implement right now:

- [Component/instance options order](https://vuejs.org/v2/style-guide/#Component-instance-options-order-recommended)
- [Single-file component top-level element order](https://vuejs.org/v2/style-guide/#Single-file-component-top-level-element-order-recommended)

A lot of other 'rules' are done in the `<template></template>` part which can be done later when support is given. Is there a plan to do this?

**Comment by j-f1** [comment]
@igeligel I don’t think so. Prettier’s goal is to manage code layout for you (parentheses, whitespace, etc.), and we recommend that you use another tool to warn you about code patterns (like method ordering, property ordering, and almost anything else you can think of).

**Comment by lehni** [comment]
@evilebottnawi will you consider the [Sass Indented Syntax](http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html) as well in your work? The `lang` identifier for it is `"sass"`.

**Comment by j-f1** [comment]
@lehni Can you open a new issue so we can discuss this separately?

**Comment by evilebottnawi** [comment]
@lehni no, we need integrate `postcss-sass` (https://github.com/jonathantneal/postcss-sass) and do a lot of work, but it is separate issue and PR welcome

**Comment by yassh** [comment]
prettier v1.11.1 has a bug.

index.vue:

```index.vue
<template>
  <span :class="$style.root"><slot /></span>
</template>

<style src="./style.css" module />
```

`prettier index.vue`:

```
<template>
  <span :class="$style.root"><slot /></span>
</template>

<style src="./style.css" module />
<template><span : class= "$style.root" ><slot / ></span> </template> <style src=
  "./style.css" module / >;
<template>
  <span :class="$style.root"><slot /></span>
</template>

<style src="./style.css" module />
```

**Comment by suchipi** [comment]
@yassh could you please open a separate issue and use the issue template?

**Comment by lipis** [comment]
@yassh here is the [link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoDOWe5SY+VVAvMSACRUwCeOcAOgBOECDHaFqOMWQD0k2TTokoqWZlwE4K0tV78yVIWDYgBi-YLDN2ZDBAAmAVwPyQAGhAQsMAJbQqZFAsIV9YAHVfBxgAC2QADgAGTxg8ACNI6LikACZPKjCAc34ARScxOGQAMzwcKjgUoTxfHCKAYQgMDDxkEChoSs80prAAazgYAGVaMCLkGCEnBpAAKyoADwAhEfGpvAw4ABkwyqQauuXaIXqhXoA3JY8QeoxfecXlp3qAFXTAs9q9U8YRuMAACk1Ct1qoDlkI4ABHJy+eEQvBQnoAi6eEIQerhJpYXohOA3O6DEB4IQiADuYKpCH+lLuECiTwcEDAMOxlO43KBXicMCwQpy-LgAF8JUA) to that example.

**Comment by yassh** [comment]
@suchipi, @lipis Thank you. I opened a issue: #4106

**Comment by wagerfield** [comment]
Thanks to all efforts on Vue support so far—looking forward to support for `<template>` formatting.

Something I have noticed is that Prettier doesn't remove extra new lines before, between and after template/script/style tags. For example:

```vue
<!-- new line -->
<!-- new line -->
<!-- new line -->
<template>
</template>
<!-- new line -->
<!-- new line -->
<!-- new line -->
<script>
</script>
<!-- new line -->
<!-- new line -->
<!-- new line -->
<style>
</style>
<!-- new line -->
<!-- new line -->
<!-- new line -->
```

...does not remove the new lines before the template tag, nor does it collapse the new lines between the template, script and style tags, nor does it remove the extra new lines after the style tag.

It would be great if Prettier could remove all newlines before the first tag, then enforce 1 new line between template/script/style tags and also a single newline at the end of the file. Following these formatting rules, the example above would become:

```vue
<template>
</template>
<!-- new line -->
<script>
</script>
<!-- new line -->
<style>
</style>
<!-- new line -->
```

I like @igeligel's suggestion for enforcing template/script/style tag order as per Vue's style guide, but also appreciate @j-f1's stance that this is not Prettier's concern.

**Comment by bencooper222** [comment]
Are there plans to do basic operator spacing and such within Vue properties? For example, right now, Prettier is fine with (this is within a `v-for` block):

`<tr :key="Math.random()+chanceObj.actual+chanceObj.normal">`

I feel like properly spacing that statement should be within the scope of Prettier

**Comment by suchipi** [comment]
@bencooper222 yes, that would be within scope once we are formatting the HTML in templates (right now we only format the JS and CSS).

**Comment by Sporradik** [comment]
Is there/will there be an option to disable all CSS formatting for .vue files?
I would like to use prettier to format the JavaScript but not the CSS.
Apologies if this is the wrong place for this question.

**Comment by suchipi** [comment]
@Sporradik probably not

**Comment by kissu** [comment]
@Sporradik if you're using prettier with ESlint you may try to override prettier's default CSS reformatting behavior with stylelint. :D

**Comment by ikatyang** [comment]
Opened #5259 to address this issue, feedbacks welcome.

**Comment by vielhuber** [comment]
Currently, the <script> and <style> parts of a Single File Component are formatted.

Are there plans of also formatting the <template>-Part? 

This is the last missing "bit" of Prettier overtaking the world.

**Comment by ikatyang** [comment]
@vielhuber See #5259.
