### ISSUE TITLE
Prefer chain on new line over arguments on own line

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#2966]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22class%20Something%20%7B%5Cn%20%20%20%20%20%20someMethod(inputThings)%20%7B%5Cn%20%20%20%20%20%20%20%20this._client%20%3D%20new%20Client()%3B%5Cn%5Cn%20%20%20%20%20%20%20%20this._someResources%20%3D%20Object.entries(inputThings)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20.map((%5Bname%2C%20%7B%20uri%20%7D%5D)%20%3D%3E%20this._client.register(%7B%20uri%2C%20name%20%7D))%3B%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A4%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--tab-width 4
```

**Input:**
```js
class Something {
      someMethod(inputThings) {
        this._client = new Client();

        this._someResources = Object.entries(inputThings)
            .map(([name, { uri }]) => this._client.register({ uri, name }));
    }
}
```

**Output:**
```js
class Something {
    someMethod(inputThings) {
        this._client = new Client();

        this._someResources = Object.entries(
            inputThings
        ).map(([name, { uri }]) => this._client.register({ uri, name }));
    }
}
```

**Expected behavior:**
Either

```js
class Something {
    someMethod(inputThings) {
        this._client = new Client();

        this._someResources = Object.entries(inputThings)
            .map(([name, { uri }]) => this._client.register({ uri, name }));
    }
}
```

or

```js
class Something {
    someMethod(inputThings) {
        this._client = new Client();

        this._someResources = Object.entries(inputThings).map(
            ([name, { uri }]) => this._client.register({ uri, name })
        );
    }
}
```

**Comment by KennethSundqvist** [comment]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEkoYIawByeAtnORXJgLyYBmArlGMWZeQBQA6IeATgHMGZWDwCUAOkbNW7Tj35CRMcQG4uzdFhz4ipOexr0mLfQYrdeg4QhUhJ0023NxLim6PuqQAGhAQABxgAS3RkUH4+CAB3AAV+BDRkXgA3CGCAE18QACM+PDAAazgYAGUAguCoAWQYPgY4Pyq0OD4YWPyBEjxkOjwAGxa-ACs0AA8AIXyiktL9ABkquF6BoZAKvha+ZJy8HIBPfuhsgL4qmAB1TJgAC2QADgAGP1OIFov8gOTTuC2U5b8fDgAEcGMEgR08F0ekg+oNGiAWiRgrV6gi0FUBP04ABFBgQeAreF+GB7K4ZW7IABMJPywX6mIAwhASN1klBoACQAwWgAVPZJWGrOAAXxFQA)
```sh
# Options (if any):
```

**Input:**
```jsx
const constantNameeeeeee = funcNameeeeeee("argument").funcNameeeeeee("argument");
const constantNameeeeeeeeeee = funcNameeeeeeeeeee("argument").funcNameeeeeeeeeee("argument");
```

**Output:**
```jsx
const constantNameeeeeee = funcNameeeeeee("argument").funcNameeeeeee(
  "argument"
);
const constantNameeeeeeeeeee = funcNameeeeeeeeeee(
  "argument"
).funcNameeeeeeeeeee("argument");
```

**Expected behavior:**

**Output:**
```jsx
const constantNameeeeeee = funcNameeeeeee("argument")
  .funcNameeeeeee("argument");
const constantNameeeeeeeeeee = funcNameeeeeeeeeee("argument")
  .funcNameeeeeeeeeee("argument");
```

**Comment by SimenB** [comment]
This has been fixed at some point to the second suggestion I had in the OP



**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22class%20Something%20%7B%5Cn%20%20%20%20%20%20someMethod(inputThings)%20%7B%5Cn%20%20%20%20%20%20%20%20this._client%20%3D%20new%20Client()%3B%5Cn%5Cn%20%20%20%20%20%20%20%20this._someResources%20%3D%20Object.entries(inputThings)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20.map((%5Bname%2C%20%7B%20uri%20%7D%5D)%20%3D%3E%20this._client.register(%7B%20uri%2C%20name%20%7D))%3B%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A4%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser babylon
--tab-width 4
```

**Input:**
```jsx
class Something {
      someMethod(inputThings) {
        this._client = new Client();

        this._someResources = Object.entries(inputThings)
            .map(([name, { uri }]) => this._client.register({ uri, name }));
    }
}
```

**Output:**
```jsx
class Something {
    someMethod(inputThings) {
        this._client = new Client();

        this._someResources = Object.entries(inputThings).map(
            ([name, { uri }]) => this._client.register({ uri, name })
        );
    }
}
```

**Comment by KennethSundqvist** [comment]
@SimenB, I suggest that we leave this open.

The issue hasn't been fixed, it's just that the specific scenario you had has changed for some reason.

For example, if we change `this._someResources` to `this._resources` it still looks bad:

```js
class Something {
    someMethod(inputThings) {
        this._client = new Client();

        this._resources = Object.entries(inputThings).map(([name, { uri }]) =>
            this._client.register({ uri, name })
        );
    }
}
```

I'm still encountering things like this in many places in my code.

**Comment by SimenB** [comment]
Fair enough
