### ISSUE TITLE
Double empty line in markdown lists changes marker

### ISSUE THREAD

**Issue by kachkaev** [prettier/prettier#4369]
Looks like two or more empty lines between both list items in markdown work as a flipper for the marker. `*` toggles to `-` and `1.` toggles to `1)` 🤷‍♀️ 

**Prettier 1.12.1**
* [Playground link - unordered list with `*`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAqABACzgGxxARgB0oSNs8IAmE2qc3fAZjocoBY6ytGIBWVj0oA2EiAA0ICAAcYAS2gBnZKACGAJ3UQA7gAUNCZSlUA3CHIAmEkACN1qsAGs4MAMrSHcqAHNkMdQCucJJeinDqMLr23gC2qsgAZqo4YZIAVooAHgBC9k4urqoxcAAyXnCJyakgHuph6sggceqOFjpQ1tLqXjAA6pYwmMgAHAAMkl0QYb320o1dcPUmFZLqcACOAXJrUaqx8UhJKcEgYTFyfoEnil7eOHAAigEQ8JXHkjCqNv0Wg8hUH3schwtwAwhAYnFGlBoCsQAEwgAVL5GI5hAC+6KAA)
* [Playground link - unordered list with `-`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABACzgGxxARgB0oSNs8IAmE2qc3fAZjocoBY6ytGIBWVj0oA2EiAA0ICAAcYAS2gBnZKACGAJ3UQA7gAUNCZSlUA3CHIAmEkACN1qsAGs4MAMrSHcqAHNkMdQCucJJeinDqMLr23gC2qsgAZqo4YZIAVooAHgBC9k4urqoxcAAyXnCJyakgHuph6sggceqOFjpQ1tLqXjAA6pYwmMgAHAAMkl0QYb320o1dcPUmFZLqcACOAXJrUaqx8UhJKcEgYTFyfoEnil7eOHAAigEQ8JXHkjCqNv0Wg8hUH3schwtwAwhAYnFGlBoCsQAEwgAVL5GI5hAC+6KAA)
* [Playground link - ordered list with `1. 2. 3.`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAdAAgBZwDZ4SoA6UpATFrgROafVAMxX6GMMAsLNHDpArN0L8GANiERRpEABoQEAA4wAltADOyUAEMATjogB3AAq6EGlFoBuEZQBNZIAEY6tYANZwYAZQWvlUAHNkGB0AVzg5fzU4HRgjFwCAWy1kADMtPGi5ACs1AA8AIRd3Ty8tRLgAGX84NIyskF8daJ1kEGSdN1tDKAcFHX8YAHU7GGxkAA4ABjl+iGihlwU2-rgWy1q5HTgAR1DlbfitJJSkdMyIkGjE5WCwy7V-ALw4AEVQiHg6i7kYLUcRrYxshyL8XMo8E8AMIQRLJNpQaCbEChaIAFX+5nO0QAvjigA)
* [Playground link - ordered list with `1) 2) 3)`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAlAAgBZwDZ4SoA6UpATFrgROafVAMxX6GMMAsLNHDpArN0L8GANiERRpEABoQEAA4wAltADOyUAEMATjogB3AAq6EGlFoBuEZQBNZIAEY6tYANZwYAZQWvlUAHNkGB0AVzg5fzU4HRgjFwCAWy1kADMtPGi5ACs1AA8AIRd3Ty8tRLgAGX84NIyskF8daJ1kEGSdN1tDKAcFHX8YAHU7GGxkAA4ABjl+iGihlwU2-rgWy1q5HTgAR1DlbfitJJSkdMyIkGjE5WCwy7V-ALw4AEVQiHg6i7kYLUcRrYxshyL8XMo8E8AMIQRLJNpQaCbEChaIAFX+5nO0QAvjigA)
* [Playground link - ordered list with `1. 1. 1.`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAdAAgBZwDZ4SoA6UpGO+hATKXVBbgRAMz2NUQAs95WThAKzt+nAGykQAGhAQADjACW0AM7JQAQwBOWiAHcACtoRqUGgG4RFAE2kgARlo1gA1nBgBlOc8VQA5sgwWgCucDK+KnBaMAZOfgC2GsgAZhp4kTIAVioAHgBCTq7uHhrxcAAyvnApaRkg3lqRWsggiVou1vpQdnJavjAA6jYw2MgAHAAMMr0QkQNOci29cE3m1TJacACOwYqbsRoJSUip6WEgkfGKgSHnKr5+eHAAisEQ8DVnMjAa9kPWI2Q1G+TkUeAeAGEIPFEi0oNB1iBgpEACq-UynSIAXyxQA)
* [Playground link - ordered list with `1) 1) 1)`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAlAAgBZwDZ4SoA6UpGO+hATKXVBbgRAMz2NUQAs95WThAKzt+nAGykQAGhAQADjACW0AM7JQAQwBOWiAHcACtoRqUGgG4RFAE2kgARlo1gA1nBgBlOc8VQA5sgwWgCucDK+KnBaMAZOfgC2GsgAZhp4kTIAVioAHgBCTq7uHhrxcAAyvnApaRkg3lqRWsggiVou1vpQdnJavjAA6jYw2MgAHAAMMr0QkQNOci29cE3m1TJacACOwYqbsRoJSUip6WEgkfGKgSHnKr5+eHAAisEQ8DVnMjAa9kPWI2Q1G+TkUeAeAGEIPFEi0oNB1iBgpEACq-UynSIAXyxQA)

**Input:**
```markdown
* hello1

* hello2


* hello3

* hello4


* hello5

* hello6
```

**Output:**
```markdown
* hello1

* hello2

- hello3

- hello4

* hello5

* hello6
```

Marker style does not fix itself even after the second format.

**Expected behavior:**

```markdown
* hello1

* hello2

* hello3

* hello4

* hello5

* hello6
```

**Comment by ikatyang** [comment]
Opened remarkjs/remark#332.

**Comment by kachkaev** [comment]
Thanks @ikatyang for opening an upstream issue. Even though remark gets three lists instead of one, what causes the markers to flip? I thought this would be the printer's job, which is a part of prettier.

**Comment by ikatyang** [comment]
See http://spec.commonmark.org/0.28/#example-264.

**Comment by ikatyang** [comment]
Their ASTs are different and it'll cause rendered HTML to be different especially if CSS applied, for example:

```md
* hello1
* hello2
- hello3
- hello4
* hello5
* hello6
```

* hello1
* hello2
- hello3
- hello4
* hello5
* hello6

**Comment by kachkaev** [comment]
To be honest, it's hard for me to imagine a scenario when someone wants to have two lists of the same kind following each other. It's much more common that there's an extra blank line after a listing etc. inside  a list item, which unexpectedly splits up the list. I have been facing this several times already and had to manually go through `1) → 1.` in diffs after running Prettier.

**Comment by kachkaev** [comment]
Yeah, I understand that there are two lists in the AST. What I'm wondering is if these lists could be ‘merged’ during printing. This would require a change in `getPrefix()`, which currently looks like this:

https://github.com/prettier/prettier/blob/1f84880fb16282f3d086de71b5ad9b4e3fca8b67/src/language-markdown/printer-markdown.js#L251-L261

E.g. roughly to this:

```js
          function getPrefix() {
            const rawPrefix = node.ordered
              ? (index === 0
                  ? node.start
                  : isGitDiffFriendlyOrderedList
                    ? 1
                    : node.start + index) + "."
              : "*";
```
(`isGitDiffFriendlyOrderedList` would just have to apply to the fist list in a sequence)

This change would not allow for two consequent lists to be rendered in the output. I know that those are supported by the spec, but I'm not sure if they are being used at all in practice. Accidental insertion of a double `\n\n` in a single list is way more common (at least, according to my own experience).

**Comment by kachkaev** [comment]
What I'm trying to say is that Prettier could have its own opinion when it comes to consequent lists of a single kind. It can just merge all such lists into a single one and thus better work for cases like:

```
* hello1

* hello2

- hello3

- hello4

* hello5

* hello6
```

(I see this list as a single list, it's just not prettified)

It's probably fine that remark detects separate lists when there's too much white space between item. there is a chance that some users of that library consider this as a correct behavior.

**Comment by ikatyang** [comment]
We can't merge them even if it's less used, [the 1st goal for a formatter is to be correct](https://prettier.io/docs/en/rationale.html#correctness), people won't trust a formatter that'll change the meaning of the code for any reason.

I believe this issue should be fixed in remark since the root cause is that it didn't follow the CommonMark spec in this case.

**Comment by joealden** [comment]
Any movement on this problem? I am still experiencing this issue on the latest version of prettier (`1.19.1`) even though I can see that the "problem" was fixed upstream (https://github.com/remarkjs/remark/issues/332).
