### ISSUE TITLE
Prettier kills unbreakable whitespace in JSX that is *rendered content*

### ISSUE THREAD

**Issue by tdd** [prettier/prettier#5077]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEA8gBYCyAngOrE7wDOADgIZhwAUAlPsADpT74ATnBjpB-NnwECAPABEcTADYQA5lOkCWuaHQC8wbXih0Avhs3QASnACO6OHRgBhFXTgHozpljhLz-Jr4EAwInqFQAUH4uDBKHjwgAMroDAyCOAC2cIL4mMEARgBWcNg4qIkW+AB8VbIMtYHRKWkZ2blKgJgEEMWluKj4ANUABcCqEMoAdFBM2abDAN3DAPx1+DIA9A1VmwrKao0CHHymIAA0ICE6JsigTIKCEADuAAr3CHTIIEwAbhA4ABNziACoIWABrERJZhgHBQVTIGCCBwXOHuQQwF5g1SZJjIVDKdwXIp0AAeACEwWBITAkrM4AAZOFwfGEuAXZiCdFfApMArkFRQYHpOEwSiAmDEZAADgADBzHu5KGCGF90o4cj8WRdhPYcMIsUwcXikASlESQO5MjhEcj2Za4ap4gBFdAQeCs832mB88UAyXIABMFyRTBwSkdzggmVxXyg0G1IHQ7gAKnzPqa2aZTEA)
```sh
--parser babylon
```

**Input:**
```jsx
function OhMyWhitespace() {
  return (
    <Dialog
      actions={actions}
      onRequestClose={onCancel}
      open={open}
      title="Supprimer un objectif"
    >
      <p>
        Supprimer l’objectif « {goal.name} » ?
      </p>
    </Dialog>
  )
}
```

**Output:**
```jsx
function OhMyWhitespace() {
  return (
    <Dialog
      actions={actions}
      onRequestClose={onCancel}
      open={open}
      title="Supprimer un objectif"
    >
      <p>
        Supprimer l’objectif «
        {goal.name}
         » ?
      </p>
    </Dialog>
  );
}

```

BTW, the output above is what I get on the playground (still unacceptable), but *not* what I get in VSCode with the Prettier extension in ESLint integration mode, where I get the opening French quote mark glued to the opening JSX expr curly. Perhaps because I use the `babel-eslint` parser?

**Expected behavior:**

If I have literal unbreakable whitespace in my contents, it's for a reason. Proper French typesetting, for instance, mandates such whitespace inside French quotation marks, or before double punctuation marks (`?!:;`).

I used Prettier 1.13.5 so far and all was dandy. Now it strips *content* from my code! Not just regular ASCII space, no! Special whitespacing too! It *changes the resulting display/contents my code produces*, which Prettier should never ever do.

**Version info**

- VSCode 1.27.1
- Prettier extension 1.6.1
- Prettier 1.14.2
- ESLint 5.5.0
- ESLint-Config-Prettier 3.0.1
- ESLint-Plugin-Prettier 2.6.2
- ESLint-Plugin-React 7.11.1

**Prettier config in `package.json` :**

```json
  "eslintConfig": {
    "extends": [
      "standard",
      "prettier",
      "plugin:react/recommended",
      "plugin:jsx-a11y/recommended",
      "plugin:import/errors"
    ],
    "plugins": [
      "prettier",
      "react",
      "jsx-a11y",
      "import"
    ],
    "parser": "babel-eslint",
    "rules": {
      "prettier/prettier": [
        "error",
        {
          "arrowParens": "always",
          "semi": false,
          "singleQuote": true,
          "trailingComma": "es5"
        }
      ],
      "no-irregular-whitespace": 0
    },
    "settings": {
      "react": {
        "version": "16.5.0"
      }
    },
    "env": {
      "browser": true,
      "commonjs": true,
      "es6": true,
      "jest": true,
      "node": true
    }
  },
```

**Comment by lydell** [comment]
Note others wanting to reproduce this: It's possible to reproduce when following the Playground link above, but copy-paste seems to normalize the non-breaking spaces to normal spaces so that won't work.

**Comment by tdd** [comment]
If you're on a Mac, Alt+Space will insert a literal unbreakable whitespace, FYI. The online Playground editor doesn't normalize it when typed in.

**Comment by duailibe** [comment]
FTR it's Github rendering that normalizes the whitespace, which is why it doesn't work when you copy from the issue.

**Comment by lydell** [comment]
In the playground, ctrl+a ctrl+c ctrl+v seems to normalize them away as well.

**Comment by duailibe** [comment]
I can't repro this on master. Maybe it got fixed by one the latest PRs..

**Comment by tdd** [comment]
Seems like https://github.com/prettier/prettier/commit/0c7c1bfde431d5810571834460be126a70bd0f30 might be the fixer, although it's a side-effect of the fix, arguably. Will have to try.

**Comment by lydell** [comment]
Yep, that should work.

**Comment by lydell** [comment]
Here's a PR adding a test case: #5138. But as mentioned in the comments for that PR, the bug isn't fully fixed.

**Comment by lydell** [comment]
When bisecting, it at first appears as if #4717 broke things. But when looking closer, I think that PR made legit changes that just exposed another bug in more cases.

As far as I can tell, the issue is that when there is a break after some JSX text that ends with whitespace (including non-breaking spaces, which are considered insignificant in JS but significant in JSX), the doc printer trims that whitespace away.

Here's some test code (there's non-breaking spaces before and after the "a", but beware that GitHub might normalize them away):

```jsx
x = <p> a </p>
```

This is the output when forcing everything to break (there's a non-breaking space before the "a", but the one after is missing):

```
$ ./bin/prettier.js test.js --print-width 1
x = (
  <p>
     a
  </p>
);
```

Here's the doc printer code that trims whitespace (commenting it out makes the missing non-breaking space after the "a" appear):

https://github.com/prettier/prettier/blob/cc83a27a3edb6fcad6da114336761adbebf9b276/src/doc/doc-printer.js#L476-L482

That code was added in #1259 by @vjeux on 2017-04-13. Back then, non-breaking spaces where converted into `&nbsp;` in JSX:

```jsx
// Normal print-width.
x = <p>&nbsp;a&nbsp;</p>;
// Short print-width.
x = (
  <p
  >
    &nbsp;a&nbsp;
  </p>
);

```

So the issue couldn't occur.

Since then, the `&nbsp;`s went away in #1165. However, that PR accidentally converted non-breaking spaces to regular spaces.

```jsx
// Normal print-width (bug: regular spaces instead of non-breaking).
x = <p> a </p>;
// Short print-width (bug: regular spaces instead of non-breaking).
x = (
  <p
  >
    {" "}
    a
    {" "}
  </p>
);
```

So the spaces were kind of preserved when breaking by turning them into `{" "}`.

After that, #1658 by @karl fixed the issue with non-breaking spaces being converted into regular spaces. And now when can observe the issue for the first time:

```jsx
// Normal print-width.
x = <p> a </p>;
// Short print-width (missing non-breaking space after the "a").
x = (
  <p
  >
     a
  </p>
);
```

So I think this bug has more or less always been there, but concealed in different ways.

How do we solve this? One way would be to turn trailing significant whitespace in JSX into `{" "}` (containing a non-breaking-space or what have you). But I wonder if the doc printer can safely assume that it can trim whitespace like that? Is that language agnostic?

@vjeux Since you added the the whitespace trimming in the doc printer, what do you think?

@karl, master of JSX in Prettier, do you have any ideas?

**Comment by vjeux** [comment]
> One way would be to turn trailing significant whitespace in JSX into {" "}

This is not correct, we want to output a `&nbsp;` if one was inputted in the first place, not a normal space.

The issue here is the doc printer removing the non breaking space. Its goal was to remove normal spaces and \t which are valid in JavaScript. I don't believe that non breaking space is a legal space in JavaScript.

So the proper fix (for correctness) here is to change the doc printer regex to only trim space and \t. I can send a PR.

**Comment by lydell** [comment]
> This is not correct, we want to output a `&nbsp;` if one was inputted in the first place, not a normal space.

For the record, I meant a `{" "}` where there's an actual non-breaking space between the quotes.

> I don't believe that non breaking space is a legal space in JavaScript.

They are legal: https://tc39.github.io/ecma262/#prod-WhiteSpace

```
WhiteSpace::
  <TAB> <VT> <FF> <SP> <NBSP> <ZWNBSP> <USP>
```

> change the doc printer regex to only trim space and \t.

I guess that makes sense anyway, since the doc printer only trims spaces that _we_ added (not spaces from the original source)? And we only ever add spaces and tabs?

**Comment by vjeux** [comment]
You are right on all accounts!

Given that the goal of removing spaces and tabs is to get rid of the ones prettier adds itself, we shouldn't need to care about all the characters indeed.

**Comment by jamietre** [comment]
Ah.... ok. I saw a bunch of jest snapshot test differences after converting a large codebase to Prettier format. Since the snapshots are formatted themselves (e.g. don't depend on the input format) I incorrectly assumed this was a material change.
